version: '3.1'

services:
  mongo:
    build: ./mongo
    restart: always
    ports:
      - 27017:27017
    container_name: chatappdb
    command: [--auth]
    volumes:
      - ./mongo/data:/data/db

  mongo-express:
    image: mongo-express
    container_name: chatappex
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: root 
